### ISSUE TITLE
Add eslint integration to github workflow

### ISSUE THREAD

**Issue by howardwang15** [uclaacm/website#67]
Codebase formatting is a little inconsistent right now

## ToDos

- [ ] Install eslint (save to dev dependencies) and create config file
- [ ] Add new script to package.json to run the linter (ie `npm run lint`)
- [ ] Add task in CI pipeline to run the lint script before a PR

**Comment by malsf21** [comment]
AFAIK some of the `eslint` stuff is bundled into CRA already. You should just need to add an `.eslintrc` and we should be good to go!

(just as a heads up, jamie did something similar for our CRA-basd app [passworks](https://github.com/uclaacm/passworks); she also added some extra `eslint` plugins, and set up a pre-commit hook to validate rules. there's also a copy-able lint github action that you can use and make required for merge!)

**Comment by BryanPan342** [comment]
Hey! Bryan here from CL :)

We are a big fan of eslint and here is the [file](https://github.com/UCLA-Creative-Labs/sunshine/blob/master/.eslintrc.js) we use for all of our projects :)

We use typescript but the I hope some of this stuff might give u a place to start!

We also use stylelint :) the standard config has proven to be sufficient for us!

**Comment by mattxwang** [comment]
Superseded by #114.
